name: CI
on:
  pull_request:
    branches: [master]
jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        volumes:
          - db:/var/lib/postgresql/data
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Using NodeJS v14.17
        uses: actions/setup-node@v2
        with:
          node-version: 14.17

      # ref: https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=path::$(yarn cache dir)"
      - name: Restoring yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.path }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build all workspaces
        run: yarn workspaces run build
      - name: Run all workspaces tests
        run: yarn workspaces run test --passWithNoTests
