version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./server/script/pg-init.sql:/docker-entrypoint-initdb.d/pg-init.sql
    ports:
      - ${DB_PORT:-5432}:5432
    tty: true

volumes:
  db:
