kind: Ingress
apiVersion: networking.k8s.io/v1

metadata:
  name: api

spec:
  rules:
  - # add a new line of `127.0.0.1 learn-k8s.dev`
    # to `/etc/hosts` to turn on this option
    # host: learn-k8s.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-redis
            port:
              number: 3000
